
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-backend
  template:
    metadata:
      labels:
        app: rag-backend
    spec:
      containers:
      - name: rag-backend
        image: us-central1-docker.pkg.dev/gcpproject-470309/rag-repo/rag-backend:latest
        ports:
        - containerPort: 8081
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret   # ✅ must match `kubectl get secrets`
              key: OPENAI_API_KEY   # ✅ must match the key inside the secret
---
apiVersion: v1
kind: Service
metadata:
  name: rag-backend-service
spec:
  selector:
    app: rag-backend
  ports:
  - port: 8081
    targetPort: 8081
